apiVersion: v1
kind: Pod
metadata:
  name: pod-node2name
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 6
        memory: 90Mi
      requests:
        cpu: 5
        memory: 90Mi
  nodeName: k8s-node2 # 指定调度到k8s-node2节点上
